# Generated by Django 2.1.5 on 2020-02-05 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_users_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_date',)},
        ),
    ]
