# Generated by Django 2.2.6 on 2019-10-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_auto_20191029_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag_sex',
            field=models.CharField(choices=[('Boy', 'Chłopiec'), ('Girl', 'Dziewczynka'), ('Unisex', 'Unisex')], default='unisex', max_length=6),
        ),
    ]
