# Generated by Django 2.2.6 on 2019-10-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_auto_20191030_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag_sex',
            field=models.CharField(choices=[('Boy', 'Chłopiec'), ('Girl', 'Dziewczynka'), ('Unisex', 'Unisex')], max_length=6),
        ),
    ]
