# Generated by Django 2.2.6 on 2019-10-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_auto_20191030_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag_age',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag_sex',
            field=models.CharField(choices=[('Boy', 'Chłopiec'), ('Girl', 'Dziewczynka'), ('Unisex', 'Unisex')], default='Unisex', max_length=6),
        ),
    ]
