# Generated by Django 2.2.6 on 2019-10-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_auto_20191030_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag_age',
            field=models.IntegerField(choices=[(1, '< 1 miesiąc'), (2, '< 3 miesiące'), (3, '< 6 miesięcy'), (4, '< 1 rok'), (5, '< 1.5 roku'), (6, '< 2 lata'), (7, 'Ponad 2 lata')], default=1, verbose_name='W wieku: '),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag_sex',
            field=models.CharField(choices=[('Boy', 'Chłopca'), ('Girl', 'Dziewczynki'), ('Unisex', 'Zarówno dla chłopca jaki i dziewczynki')], default='Unisex', max_length=6, verbose_name='Ubranie przeznaczone dla: '),
        ),
    ]
