# Generated by Django 2.2.6 on 2019-10-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_auto_20191030_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Dodaj nazwę produktu ( będzie widoczna na stronie marketu): '),
        ),
    ]
