# Generated by Django 2.1.5 on 2020-02-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_auto_20200218_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_1',
            field=models.ImageField(default='default_1.jpg', upload_to='product_pics', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_2',
            field=models.ImageField(default='default_1.jpg', upload_to='product_pics', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_3',
            field=models.ImageField(default='default_1.jpg', upload_to='product_pics', verbose_name=''),
        ),
    ]
