# Generated by Django 2.1.5 on 2020-04-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0021_auto_20200325_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
