# Generated by Django 2.1.5 on 2020-02-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interested_age_tag',
            field=models.IntegerField(choices=[(1, '< 1 miesiąc'), (2, '< 3 miesiące'), (3, '< 6 miesięcy'), (4, '< 1 rok'), (5, '< 1.5 roku'), (6, '< 2 lata'), (7, 'Ponad 2 lata')], default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='interested_sex_tag',
            field=models.CharField(choices=[('Boy', 'Chłopca'), ('Girl', 'Dziewczynki'), ('Unisex', 'Zarówno dla chłopca jaki i dziewczynki')], default='Unisex', max_length=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='sold_age_tag',
            field=models.IntegerField(choices=[(1, '< 1 miesiąc'), (2, '< 3 miesiące'), (3, '< 6 miesięcy'), (4, '< 1 rok'), (5, '< 1.5 roku'), (6, '< 2 lata'), (7, 'Ponad 2 lata')], default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='sold_sex_tag',
            field=models.CharField(choices=[('Boy', 'Chłopca'), ('Girl', 'Dziewczynki'), ('Unisex', 'Zarówno dla chłopca jaki i dziewczynki')], default='Unisex', max_length=6),
        ),
    ]
