# Generated by Django 2.1.5 on 2020-02-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200205_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interested_age_tag',
            field=models.IntegerField(choices=[(1, '< 1 miesiąca'), (2, '< 3 miesiący'), (3, '< 6 miesięcy'), (4, '< 1 rok'), (5, '< 1.5 roku'), (6, '< 2 lat'), (7, 'Ponad 2 lat')], default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interested_sex_tag',
            field=models.CharField(choices=[('Boy', 'chłopca'), ('Girl', 'dziewczynki'), ('Unisex', 'zarówno dla chłopca jaki i dziewczynki')], default='Unisex', max_length=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sold_age_tag',
            field=models.IntegerField(choices=[(1, '< 1 miesiąca'), (2, '< 3 miesiący'), (3, '< 6 miesięcy'), (4, '< 1 rok'), (5, '< 1.5 roku'), (6, '< 2 lat'), (7, 'Ponad 2 lat')], default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sold_sex_tag',
            field=models.CharField(choices=[('Boy', 'chłopca'), ('Girl', 'dziewczynki'), ('Unisex', 'zarówno dla chłopca jaki i dziewczynki')], default='Unisex', max_length=6),
        ),
    ]
