# Generated by Django 2.1.5 on 2020-02-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200205_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interested_sex_tag',
            field=models.CharField(choices=[('Boy', ' dla chłopca'), ('Girl', 'dla dziewczynki'), ('Unisex', 'zarówno dla chłopca jaki i dziewczynki')], default='Unisex', max_length=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sold_sex_tag',
            field=models.CharField(choices=[('Boy', ' dla chłopca'), ('Girl', 'dla dziewczynki'), ('Unisex', 'zarówno dla chłopca jaki i dziewczynki')], default='Unisex', max_length=6),
        ),
    ]
