# Generated by Django 2.1.5 on 2020-03-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger_system', '0003_message_read_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='read_at',
            field=models.BooleanField(default=False),
        ),
    ]
