# Generated by Django 2.1.5 on 2020-04-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger_system', '0004_auto_20200330_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='read_at',
        ),
        migrations.AddField(
            model_name='message',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
